### ISSUE TITLE
Update instructions to pip install assemblyai[extras]

### ISSUE THREAD

**Issue by semihsezer** [AssemblyAI/assemblyai-python-sdk#23]
Instructions can be updated for a smoother start. It looks like `pip install assemblyai[extras]` is a requirement to get any python imports to work.

Expected this to work as per the instructions:
1. `pip3 install assemblyai`
2. `import assemblyai as aai`

But got:
```
File ~/Library/Python/3.9/lib/python/site-packages/assemblyai/extras.py:7
      5     import pyaudio
      6 except ImportError:
--> 7     raise ImportError(
      8         "You must install the extras for this SDK to use this feature. "

ImportError: You must install the extras for this SDK to use this feature. Run `pip install assemblyai[extras]` to install the extras. Make sure to install `apt install portaudio19-dev` (Debian/Ubuntu) or `brew install portaudio` (MacOS) before installing the extras.
```

Then had to do these other steps to be able to get the python import to work:
3.  `brew install portaudio` - works fine
4. `pip install assemblyai[extras]`

Correct instructions:
1. `pip3 install 'assemblyai[extras]'`
2. `brew install portaudio`

The instructions on the activations page should also reflect this:
<img width="847" alt="Screenshot 2023-06-23 at 12 22 46 PM" src="https://github.com/AssemblyAI/assemblyai-python-sdk/assets/12139945/edb59dc8-92a1-47d6-a197-8f0598365122">

Python 3.9.6
IPython 8.12.0
macOS Ventura 13.3

**Comment by s0h3yl** [comment]
Hi @semihsezer,

Thank you for the heads-up!

We fixed it in version `0.12.0`. 

Feel free to reopen this issue if you still experience the problem.
