### ISSUE TITLE
Can a stored `word_boost` be used on a local file

### ISSUE THREAD

**Issue by camstuart** [AssemblyAI/assemblyai-python-sdk#25]
Hello,

Is it possible to use the: `transcriber = aai.Transcriber()` library and specify word boost which remains stored for the life of the instance, instead of uploading it on every request?

EG:

```python
transcriber = aai.Transcriber(config={"word_boost": ["foo", "bar"], "boost_param": "default"}) # Stored on assembly ai servers
transcript = transcriber.transcribe("./my-local-audio-file.wav") # Word boost applied
```

Thanks

**Comment by oconnoob** [comment]
Hey @camstuart!

If my understanding is correct, I think you're looking for something like below:

```python
import assemblyai as aai


aai.settings.api_key = "your-key"

config = aai.TranscriptionConfig(word_boost=["foo", "bar"], boost_param=aai.WordBoost.default)

transcriber = aai.Transcriber(config=config)
transcript = transcriber.transcribe("./my-local-audio-file.wav")

print(transcriber.config.word_boost)
print(transcript.text)
```

`Transcriber` objects are contained locally in memory and require a `TranscriptionConfig` to be passed for the `config` parameter.

Please let me know if that isn't what you were looking for!

**Comment by oconnoob** [comment]
Closing due to stagnation. Please let me know if this needs to be reopened!
