### ISSUE TITLE
Compatibility with pydantic v2

### ISSUE THREAD

**Issue by oscarelotero** [AssemblyAI/assemblyai-python-sdk#26]
I am using a FastAPI application with Pydantic v2, and there are compatibility issues when I try to use AssemblyAI. 
The error is 
`pydantic.errors.PydanticImportError: 'BaseSettings' has been moved to the 'pydantic-settings' package.`

My stack and versions:
FastAPI==0.100.0
pydantic==2.0.2
assemblyai==0.12.0

**Comment by s0h3yl** [comment]
Hi @oscarelotero,

Thanks for the heads-up! :rocket: 

We released a fix for that in #27. This should allow you to install `pydantic>=2`.

Changes have been released in version `0.13.0`.

Let me know whether this unblocks you!

**Comment by oscarelotero** [comment]
Thanks @s0h3yl , Perfect! 
However, checking the PR, I see that BaseSettings is being imported from Pydantic directly:
https://github.com/AssemblyAI/assemblyai-python-sdk/blob/master/assemblyai/types.py#L6 
But in the Pydantic [docs](https://docs.pydantic.dev/latest/usage/pydantic_settings/) the BaseSettings requires another package: `pydantic-settings`
Could you please verify this?
Thanks again!

**Comment by s0h3yl** [comment]
Hi @oscarelotero, 

> Could you please verify this?

We have automated tests that do this, but I verified it for you manually :slightly_smiling_face: 

```
# will fail

FastAPI==0.100.0
pydantic==2.0.2
assemblyai==0.12.0 # <-- old version
```

```
# will work

FastAPI==0.100.0
pydantic==2.0.2
assemblyai==0.13.0 # <--- latest version
```

> But in the Pydantic [docs](https://docs.pydantic.dev/latest/usage/pydantic_settings/) the BaseSettings requires another package: `pydantic-settings`

This is not affecting us, as we are doing this:

```python
try:
    # for users that have installed `pydantic<2`
    from pydantic import UUID4, BaseModel, BaseSettings, Extra, Field
except ImportError:
    # for users that have installed `pydantic>=2`
    # NOTE: usage of `.v1` package that is available as of `pydantic>=2`
    from pydantic.v1 import UUID4, BaseModel, BaseSettings, Extra, Field
```

**Comment by oscarelotero** [comment]
Got it!!
Thank you so much.

You can close the issue now.

**Comment by s0h3yl** [comment]
Thank you, @oscarelotero!
