### ISSUE TITLE
No ability to set transcribe pcm_mulaw when using RealtimeTranscriber

### ISSUE THREAD

**Issue by peterhanlon** [AssemblyAI/assemblyai-python-sdk#49]
I would like to transcribe mulaw audio using the python SDK. However there doesn't appear to be any way to specify the encoding to be pcm_mulaw using the RealtimeTranscriber.

**Comment by ploeber** [comment]
Hi @peterhanlon , thanks for reporting and sorry for the late reply! We'll ship a fix soon

**Comment by ploeber** [comment]
Hi, the feature was added in the 0.21.0 version:
- https://github.com/AssemblyAI/assemblyai-python-sdk/releases/tag/0.21.0
- See also our [API docs](https://www.assemblyai.com/docs/speech-to-text/real-time#specify-the-encoding) to learn how to use the new `encoding` parameter
