### ISSUE TITLE
Add Transcript deletion support

### ISSUE THREAD

**Issue by ploeber** [AssemblyAI/assemblyai-python-sdk#56]
Support https://www.assemblyai.com/docs/api-reference/transcript#delete-a-transcript
-> Add `Transcript.delete_by_id()` and `delete_by_id_async()`

**Comment by Swimburger** [comment]
Based on what I've seen from the Python SDK, you can call methods on the transcript.
Maybe delete could be added as an instance method too, like `my_transcript.delete()` and `my_transcript.delete_async()`.
