### ISSUE TITLE
Add file upload function

### ISSUE THREAD

**Issue by ploeber** [AssemblyAI/assemblyai-python-sdk#59]
- Add `Transcriber.upload()` and `Transcriber.upload_async()`
- support path and `BinaryIO` 
- add deprecation warning to `extras.file_from_stream`.

alternative approach, to be discussed:
- or introduce new module `files`? Eg. `aai.files.upload()` (like Node SDK)

**Comment by Swimburger** [comment]
If you're going to add upload file functionality to the `Transcriber`, I would name it `Transcriber.upload_file` and `Transcriber.upload_file_async`, because otherwise there's no mention of what you're trying to upload.
