### ISSUE TITLE
Need To Add redact_pii_audio_quality Option

### ISSUE THREAD

**Issue by dweekly** [AssemblyAI/assemblyai-python-sdk#65]
The Python SDK does not support clients setting redact_pii_audio_quality - the default is "mp3", but the curl API supports "wav" as an option. The option to have WAV PII audio redacted should be added/supported.

**Comment by dweekly** [comment]
See https://github.com/AssemblyAI/assemblyai-python-sdk/pull/66 for naive first-pass implementation.

**Comment by ploeber** [comment]
Thanks for the contribution! I left a review, almost looks good :)
