### ISSUE TITLE
Cannot convert numbers to their written format

### ISSUE THREAD

**Issue by Rumeysakeskin** [AssemblyAI/assemblyai-python-sdk#69]
I need timestamps of numbers but transcriptions do not give correct timestamps. I get it as follows:

`[{'token': '105', 'start': 0, 'end': 300}, {'token': '279', 'start': 300, 'end': 600}, {'token': '164', 'start': 600, 'end': 900}, {'token': '223', 'start': 900, 'end': 1200}, {'token': '172', 'start': 1200, 'end': 1500}, {'token': '103', 'start': 1500, 'end': 1800}, {'token': '12', 'start': 1800, 'end': 2100}]`

But my audio duration is 11 seconds.

I think I will fix this if I get the numbers in text format. Because this ASR works very well for text. But
`config = aai.TranscriptionConfig(speech_model=aai.SpeechModel.best, language_code="tr", format_text=False)`
this also not worked.

How can I fix this problem?

**Comment by ploeber** [comment]
Hi @Rumeysakeskin, apologies for the late reply.
I'm not sure if I understand this correctly. Can you clarify what you mean?

Are you saying that you have audio data that contains spoken numbers? And then the timestamps don't work?

Do you have an example for me to investigate this? I"m happy to look into it

**Comment by Rumeysakeskin** [comment]
Hi @ploeber, 
The start and end times are displayed in seconds here:
`[{'token': '105', 'start': 0, 'end': 300}, {'token': '279', 'start': 300, 'end': 600}, {'token': '164', 'start': 600, 'end': 900}, {'token': '223', 'start': 900, 'end': 1200}, {'token': '172', 'start': 1200, 'end': 1500}, {'token': '103', 'start': 1500, 'end': 1800}, {'token': '12', 'start': 1800, 'end': 2100}]`

For example, the number 12 is shown to end at the 2 second, but my audio recording is 11 seconds long. In general, each number seems to take 0.3 seconds to say, but in the audio recording it takes longer. This means timestamps are not working properly.
I thought maybe if I could get it to recognize numbers in text format this could be fixed as it works fine with text input, but I couldn't do that either.

**Comment by ploeber** [comment]
Thank you for clarifying! I will forward it to our engineering team to investigate. Do you maybe have an example audio file we can use to reproduce this issue?

**Comment by MLawlz** [comment]
Hi @Rumeysakeskin! Thanks for surfacing this. Just so we can get you properly connected to our team, could you reach out to support@assemblyai.com to create a ticket with us? If you have a transcript ID for these results or the audio file that led to these timestamps, we'd be happy to help investigate!

**Comment by Rumeysakeskin** [comment]
Hi @MLawlz, @ploeber ,  I appreciate your interest!  I shared the code and audio file as a zip format.

```python
import assemblyai as aai
import re

def aai_transcribe(wav_audio_path):
    # Replace with your API key
    aai.settings.api_key = ""

    config = aai.TranscriptionConfig(speech_model=aai.SpeechModel.best, language_code="tr", format_text=False)
    transcriber = aai.Transcriber(config=config)
    transcript = transcriber.transcribe(wav_audio_path)

    if transcript.status == aai.TranscriptStatus.error:
        print(transcript.error)
        return None
    else:
        print("transcript:",transcript.words)

transcription = aai_transcribe("turkish_numbers.wav")
```

`transcript: [Word(text='105,', start=0, end=300, confidence=0.5, speaker=None), Word(text='279,', start=300, end=600, confidence=0.5, speaker=None), Word(text='164,', start=600, end=900, confidence=0.5, speaker=None), Word(text='223,', start=900, end=1200, confidence=0.5, speaker=None), Word(text='172,', start=1200, end=1500, confidence=0.5, speaker=None), Word(text='103,', start=1500, end=1800, confidence=0.5, speaker=None), Word(text='12', start=1800, end=2100, confidence=0.5, speaker=None)]`

```python
import IPython
IPython.display.Audio("turkish_numbers.wav")
```

[turkish_numbers.zip](https://github.com/user-attachments/files/16155551/turkish_numbers.zip)
