### ISSUE TITLE
Random whitespace in Chinese/Cantonese transcription

### ISSUE THREAD

**Issue by scottyeung** [AssemblyAI/assemblyai-python-sdk#88]
Hi there,

First off thanks for making this great transcription API. I bumped into issues where the result from `transcript.export_subtitles_srt()` where it gives output with random whitespace between Chinese characters

`1\n00:00:02,408 --> 00:00:06,070\n我點 解要 搞 到咁 樣 原因 係 因為 香港 人\n\n2\n00:00:06,570 --> 00:00:09,292\n都 唔 知 我 講乜點 解 我 要 講幾句 廣東話 都 冇 人理 我 呢\n\n3\n00:00:09,792 --> 00:00:10,352\n其實 係 因為 好多 嘢 都 係 命中注定\n\n`

How can I sanitise the output from my end?

**Comment by ploeber** [comment]
Hi, thanks for reporting! Can you share the corresponding transcript ID so we can take a look?

Does the normal transcript `text` also contain random whitespace?

**Comment by scottyeung** [comment]
Hi @ploeber, thanks for getting back. Here's the transcript ID - `72721e5a-fdc6-4bca-bfdb-bf0977c514f6`

**Comment by ploeber** [comment]
Hi @scottyeung. Turns out we don't support subtitles for Chinese, so the returned subtitles may not be accurate. I will follow up with engineering because the API should return an error instead of false subtitles.

**Comment by scottyeung** [comment]
Hi there, actually what you provided as transcription in Chinese and
Cantonese are more accurate than Whisper.

Please don’t return it as error.
