### ISSUE TITLE
Return the auto detected language (and confidence)

### ISSUE THREAD

**Issue by nilsjesper** [AssemblyAI/assemblyai-python-sdk#90]
We're using `language_detection=True,` when generating transcripts but the return object doesn't seem to specify the detected language or the confidence. Both of these are present in the raw API request if you use the REST API. Would it be possible to add these to the sdk as well?

**Comment by ploeber** [comment]
Hi @nilsjesper . Can you check if you're on the latest SDK version? Those fields should also be available in the SDK, e.g.

```python
print(transcript.json_response["language_confidence"])
```
