### ISSUE TITLE
TranscriptionConfig custom spellings property raises error fetching valid custom spelling config

### ISSUE THREAD

**Issue by danieljnchen** [AssemblyAI/assemblyai-python-sdk#92]
[TranscriptionConfig.set_custom_spelling](https://github.com/AssemblyAI/assemblyai-python-sdk/blob/master/assemblyai/types.py#L1225) sets the raw transcription config's `from` to a list, but [TranscriptionConfig.custom_spelling](https://github.com/AssemblyAI/assemblyai-python-sdk/blob/master/assemblyai/types.py#L918) property raises an error if `from` is not a string.

```
>>> import assemblyai as aai
>>> tc = aai.TranscriptionConfig(custom_spelling={"a": ["b", "c"]})
>>> tc.custom_spelling
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielchen/.local/share/virtualenvs/transcribe_audio-AdYllNfC/lib/python3.11/site-packages/assemblyai/types.py", line 930, in custom_spelling
    raise ValueError("`from` argument must be a string!")
ValueError: `from` argument must be a string!
```

**Comment by ploeber** [comment]
Thanks for reporting! I'll create a fix for the next version
