### ISSUE TITLE
package is shipping `tests/` folder in pypi

### ISSUE THREAD

**Issue by EmersonDove** [AssemblyAI/assemblyai-python-sdk#93]
Hey there, we realized today that installing the assembly package breaks our test suite because you're bundling your `tests` folder to the final distribution. This results in a `tests` folder in the `site-packages` folder which takes import precedence over any other package importing from `tests` (i.e `from tests.helpers import helper` resolves to assembly's tests)

We'll make our own distribution of the package to remedy this but I wanted to post the issue here.

**Comment by EmersonDove** [comment]
Intermediary fix public at [https://pypi.org/project/newassemblyai/](https://pypi.org/project/newassemblyai/) or `pip install newassemblyai` for anyone else

**Comment by ploeber** [comment]
Thanks for reporting! I'll take a look
