### ISSUE TITLE
get_sentences incorrectly splits text

### ISSUE THREAD

**Issue by igo** [AssemblyAI/assemblyai-python-sdk#99]
Text splitting needs to be more meaningful. For example text "Dr. Feynman used..." is incorrectly split by `get_sentences()` to "Dr." and "Feynman used..."

**Comment by ploeber** [comment]
Hi! Thanks for the feedback, I'll forward it to our research/eng team

**Comment by marcusolsson** [comment]
Closing as this needs to be handled in the API rather than in the Python SDK.

**Comment by igo** [comment]
@marcusolsson so is this going to be solved elsewhere?

**Comment by marcusolsson** [comment]
We've forwarded the feedback to the team and the issue is being tracked internally. Once addressed it'll work without needing to upgrade the Python package.
